# Generated by Django 6.0.6 on 2026-09-26 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalayerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text='The object-store URI of the file', max_length=1000, null=True, unique=True)),
                ('key', models.CharField(help_text='The object key/path within the datalayer bucket.', max_length=1000)),
                ('bucket', models.CharField(help_text='The datalayer bucket/service this store belongs to.', max_length=1000)),
                ('original_file_name', models.CharField(blank=True, help_text='The original client-provided file name.', max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The client-provided content type for the uploaded file.', max_length=255, null=True)),
                ('populated', models.BooleanField(default=False, help_text='Whether the store has been populated with a valid path and is ready for use.')),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='How many bytes this store actually holds, measured when the upload was finished. Null while an upload is unfinished, or for stores written before this was recorded', null=True)),
                ('orphaned_at', models.DateTimeField(blank=True, db_index=True, help_text='When the last data row referencing this store was deleted, or null while it is still in use. A *candidate* for garbage collection, not an authority: `purge_orphaned_stores` re-checks for referrers before deleting anything, and clears this again if the store was re-attached in the meantime', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who requested the upload grant, whose storage quota the bytes count against. Null for stores written before this was recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this store belongs to.', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigFileStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
    ]
