"""The kuvert data model.

``VectorExtension`` creates ``vector`` (pgvector) in this database for message embeddings; it is
not a trusted extension, so this needs the superuser -- which is what the services connect as.
On a cluster whose init script already created it (daten images carry pgvector) it is a no-op.
"""

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A display name for the mailbox (e.g. 'Work').", max_length=200)),
                ('email_address', models.CharField(help_text="The mailbox's address; the From of sent mail.", max_length=320)),
                ('display_name', models.CharField(blank=True, default='', help_text='The sender name of sent mail.', max_length=200)),
                ('provider', models.CharField(choices=[('GENERIC', 'Any IMAP/POP3 server'), ('GMAIL', 'Gmail / Google Workspace'), ('MICROSOFT', 'Outlook.com / Microsoft 365')], default='GENERIC', help_text='Who hosts the mailbox.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Linked; syncs and sends'), ('NEEDS_REAUTH', 'The credentials stopped working; update the password or link again'), ('DISABLED', 'Paused by a user; neither synced nor used to send')], default='ACTIVE', help_text='Where the mailbox is in its lifecycle.', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Only the member who linked it'), ('SHARED', 'The member who linked it and the members it is shared with'), ('ORGANIZATION', 'Every member of the organization (a team mailbox)')], default='PRIVATE', help_text='Who in the organization sees the mailbox and its mail.', max_length=20)),
                ('protocol', models.CharField(choices=[('IMAP', 'IMAP: folders, flags and moves live on the server'), ('POP3', 'POP3: one inbox, downloaded; flags are local')], default='IMAP', help_text='How incoming mail is read.', max_length=10)),
                ('incoming_host', models.CharField(help_text='The IMAP or POP3 server.', max_length=255)),
                ('incoming_port', models.PositiveIntegerField(help_text='The IMAP or POP3 port.')),
                ('incoming_security', models.CharField(choices=[('TLS', 'Implicit TLS (IMAPS 993, POP3S 995, SMTPS 465)'), ('STARTTLS', 'Plain connection upgraded with STARTTLS (IMAP 143, POP3 110, SMTP 587)'), ('NONE', 'No encryption (only when the deployment allows it)')], default='TLS', help_text='Transport security of the incoming connection.', max_length=10)),
                ('smtp_host', models.CharField(blank=True, help_text='The SMTP server; without one the mailbox cannot send.', max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, help_text='The SMTP port.', null=True)),
                ('smtp_security', models.CharField(choices=[('TLS', 'Implicit TLS (IMAPS 993, POP3S 995, SMTPS 465)'), ('STARTTLS', 'Plain connection upgraded with STARTTLS (IMAP 143, POP3 110, SMTP 587)'), ('NONE', 'No encryption (only when the deployment allows it)')], default='TLS', help_text='Transport security of the SMTP connection.', max_length=10)),
                ('username', models.CharField(help_text='The login name (usually the address).', max_length=320)),
                ('auth_method', models.CharField(choices=[('PASSWORD', 'Username and (app) password'), ('XOAUTH2', 'OAuth 2.0 access token (SASL XOAUTH2)')], default='PASSWORD', help_text='How the service logs in.', max_length=10)),
                ('secret', models.TextField(blank=True, help_text='Encrypted password (PASSWORD) or refresh token (XOAUTH2). Never exposed.', null=True)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token. Never exposed.', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the stored access token runs out.', null=True)),
                ('smtp_username', models.CharField(blank=True, help_text='A separate SMTP login, when the server wants one; else `username`.', max_length=320, null=True)),
                ('smtp_secret', models.TextField(blank=True, help_text='Encrypted separate SMTP password. Never exposed.', null=True)),
                ('save_sent_copy', models.BooleanField(default=True, help_text='Append sent mail to the Sent folder (off for Gmail and Microsoft, which keep a copy themselves).')),
                ('pop_leave_on_server', models.BooleanField(default=True, help_text='POP3: keep downloaded mail on the server. Off deletes it there once stored.')),
                ('capabilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='What the incoming server announced (IMAP CAPABILITY, POP3 CAPA).')),
                ('sync_lease_until', models.DateTimeField(blank=True, help_text='Held by a running sync until then.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When the last successful sync finished.', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Why the last sync or connection failed, if it did.', null=True)),
                ('last_error_code', models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error')], help_text='The machine-readable kind of `last_error`.', max_length=30, null=True)),
                ('backfill_done', models.BooleanField(default=False, help_text='Every synced folder has reached the backfill window.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the mailbox was linked.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the mailbox settings last changed.')),
                ('creator', models.ForeignKey(blank=True, help_text='The member who linked the mailbox; only they change its credentials or sharing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this mailbox belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to='authentikate.organization')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Members who see the mailbox when it is SHARED.', related_name='shared_mail_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMailAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="A display name for the mailbox (e.g. 'Work').", max_length=200)),
                ('email_address', models.CharField(help_text="The mailbox's address; the From of sent mail.", max_length=320)),
                ('display_name', models.CharField(blank=True, default='', help_text='The sender name of sent mail.', max_length=200)),
                ('provider', models.CharField(choices=[('GENERIC', 'Any IMAP/POP3 server'), ('GMAIL', 'Gmail / Google Workspace'), ('MICROSOFT', 'Outlook.com / Microsoft 365')], default='GENERIC', help_text='Who hosts the mailbox.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Linked; syncs and sends'), ('NEEDS_REAUTH', 'The credentials stopped working; update the password or link again'), ('DISABLED', 'Paused by a user; neither synced nor used to send')], default='ACTIVE', help_text='Where the mailbox is in its lifecycle.', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Only the member who linked it'), ('SHARED', 'The member who linked it and the members it is shared with'), ('ORGANIZATION', 'Every member of the organization (a team mailbox)')], default='PRIVATE', help_text='Who in the organization sees the mailbox and its mail.', max_length=20)),
                ('protocol', models.CharField(choices=[('IMAP', 'IMAP: folders, flags and moves live on the server'), ('POP3', 'POP3: one inbox, downloaded; flags are local')], default='IMAP', help_text='How incoming mail is read.', max_length=10)),
                ('incoming_host', models.CharField(help_text='The IMAP or POP3 server.', max_length=255)),
                ('incoming_port', models.PositiveIntegerField(help_text='The IMAP or POP3 port.')),
                ('incoming_security', models.CharField(choices=[('TLS', 'Implicit TLS (IMAPS 993, POP3S 995, SMTPS 465)'), ('STARTTLS', 'Plain connection upgraded with STARTTLS (IMAP 143, POP3 110, SMTP 587)'), ('NONE', 'No encryption (only when the deployment allows it)')], default='TLS', help_text='Transport security of the incoming connection.', max_length=10)),
                ('smtp_host', models.CharField(blank=True, help_text='The SMTP server; without one the mailbox cannot send.', max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, help_text='The SMTP port.', null=True)),
                ('smtp_security', models.CharField(choices=[('TLS', 'Implicit TLS (IMAPS 993, POP3S 995, SMTPS 465)'), ('STARTTLS', 'Plain connection upgraded with STARTTLS (IMAP 143, POP3 110, SMTP 587)'), ('NONE', 'No encryption (only when the deployment allows it)')], default='TLS', help_text='Transport security of the SMTP connection.', max_length=10)),
                ('username', models.CharField(help_text='The login name (usually the address).', max_length=320)),
                ('auth_method', models.CharField(choices=[('PASSWORD', 'Username and (app) password'), ('XOAUTH2', 'OAuth 2.0 access token (SASL XOAUTH2)')], default='PASSWORD', help_text='How the service logs in.', max_length=10)),
                ('smtp_username', models.CharField(blank=True, help_text='A separate SMTP login, when the server wants one; else `username`.', max_length=320, null=True)),
                ('save_sent_copy', models.BooleanField(default=True, help_text='Append sent mail to the Sent folder (off for Gmail and Microsoft, which keep a copy themselves).')),
                ('pop_leave_on_server', models.BooleanField(default=True, help_text='POP3: keep downloaded mail on the server. Off deletes it there once stored.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the mailbox was linked.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The member who linked the mailbox; only they change its credentials or sharing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this mailbox belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='mail.mailaccount')),
            ],
            options={
                'verbose_name': 'historical mail account',
                'verbose_name_plural': 'historical mail accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="The folder's full name on the server, decoded (e.g. 'INBOX/Receipts').", max_length=1000)),
                ('name', models.CharField(help_text='The last segment of the path.', max_length=1000)),
                ('delimiter', models.CharField(blank=True, help_text="The server's hierarchy delimiter.", max_length=5, null=True)),
                ('role', models.CharField(choices=[('INBOX', 'Incoming mail'), ('SENT', 'Sent mail'), ('DRAFTS', 'Drafts'), ('TRASH', 'Deleted mail'), ('ARCHIVE', 'Archived mail'), ('JUNK', 'Spam'), ('ALL', "Every message (Gmail's All Mail)"), ('FLAGGED', 'A virtual folder of flagged mail'), ('OTHER', 'A user folder')], default='OTHER', help_text='What the folder is for.', max_length=10)),
                ('selectable', models.BooleanField(default=True, help_text='Whether the folder can hold messages (\\Noselect folders only hold folders).')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether syncs read this folder.')),
                ('exists_on_server', models.BooleanField(default=True, help_text='False once the server stopped listing the folder.')),
                ('uidvalidity', models.BigIntegerField(blank=True, help_text="The folder's UIDVALIDITY when last synced; a change invalidates every stored UID.", null=True)),
                ('highest_modseq', models.BigIntegerField(blank=True, help_text='CONDSTORE: the HIGHESTMODSEQ when flags were last read.', null=True)),
                ('last_uid', models.BigIntegerField(default=0, help_text='The highest UID stored; new mail is everything above it.')),
                ('oldest_uid', models.BigIntegerField(blank=True, help_text='The lowest UID stored by the backfill.', null=True)),
                ('backfill_done', models.BooleanField(default=False, help_text='The backfill reached the window (or the first message).')),
                ('total_count', models.IntegerField(default=0, help_text='Messages in the folder, as the server counts them.')),
                ('unread_count', models.IntegerField(default=0, help_text='Unread messages in the folder, as the server counts them.')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When the folder was last synced.', null=True)),
                ('account', models.ForeignKey(help_text='The mailbox this folder is in.', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mail.mailaccount')),
            ],
            options={
                'ordering': ['account', 'path'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200)),
                ('uid', models.BigIntegerField(blank=True, help_text="IMAP: the UID within the folder's UIDVALIDITY.", null=True)),
                ('uidvalidity', models.BigIntegerField(blank=True, help_text='IMAP: the UIDVALIDITY the UID belongs to.', null=True)),
                ('uidl', models.CharField(blank=True, help_text="POP3: the server's unique id.", max_length=100, null=True)),
                ('message_id', models.CharField(blank=True, help_text='The Message-ID header, without angle brackets.', max_length=998, null=True)),
                ('in_reply_to', models.CharField(blank=True, help_text='The In-Reply-To header, without angle brackets.', max_length=998, null=True)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=998), blank=True, default=list, help_text='The References header, oldest first.')),
                ('subject', models.TextField(blank=True, default='', help_text='The decoded subject.')),
                ('sender_name', models.CharField(blank=True, default='', help_text='The From display name.', max_length=500)),
                ('sender_address', models.CharField(blank=True, default='', help_text='The From address, lower-cased.', max_length=320)),
                ('reply_to', models.JSONField(blank=True, default=list, help_text='Reply-To addresses: [{name, address}].')),
                ('to', models.JSONField(blank=True, default=list, help_text='To addresses: [{name, address}].')),
                ('cc', models.JSONField(blank=True, default=list, help_text='Cc addresses: [{name, address}].')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='Bcc addresses (only on sent mail): [{name, address}].')),
                ('date', models.DateTimeField(blank=True, help_text='The Date header (else when the server received it).', null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='When the server received the message (IMAP INTERNALDATE).', null=True)),
                ('snippet', models.CharField(blank=True, default='', help_text='The start of the text, for list views.', max_length=300)),
                ('text_body', models.TextField(blank=True, default='', help_text='The plain-text body (converted from HTML when there is none).')),
                ('html_body', models.TextField(blank=True, default='', help_text='The HTML body, sanitized (no scripts, handlers, forms); remote images are kept here and stripped on read unless asked for.')),
                ('has_remote_images', models.BooleanField(default=False, help_text='The HTML loads images from the internet.')),
                ('size', models.IntegerField(default=0, help_text='The message size in bytes.')),
                ('flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='IMAP flags and keywords (\\Seen, \\Flagged, \\Answered, \\Draft, $Label…).')),
                ('has_attachments', models.BooleanField(default=False, help_text='The message has attachments (not counting inline images).')),
                ('truncated', models.BooleanField(default=False, help_text='The message was larger than the sync limit; only its headers are stored.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was first stored.')),
                ('account', models.ForeignKey(help_text='The mailbox.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailaccount')),
                ('folder', models.ForeignKey(help_text='The folder the message is in.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailfolder')),
                ('raw', models.ForeignKey(blank=True, help_text='The raw RFC 5322 message in the datalayer (null without one).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='datalayer.bigfilestore')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text="The part's position among the message's attachments.")),
                ('filename', models.CharField(blank=True, default='', help_text='The file name, as the sender gave it.', max_length=1000)),
                ('content_type', models.CharField(help_text='The MIME type.', max_length=255)),
                ('size', models.IntegerField(default=0, help_text='The decoded size in bytes.')),
                ('content_id', models.CharField(blank=True, help_text='The Content-ID an HTML body references (cid:), without angle brackets.', max_length=998, null=True)),
                ('inline', models.BooleanField(default=False, help_text='Shown inside the HTML body (an inline image), not as a download.')),
                ('store', models.ForeignKey(blank=True, help_text='The bytes in the datalayer (null without one).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='datalayer.bigfilestore')),
                ('message', models.ForeignKey(help_text='The message the file is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.message')),
            ],
            options={
                'ordering': ['message', 'position'],
            },
        ),
        migrations.CreateModel(
            name='OAuthLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GENERIC', 'Any IMAP/POP3 server'), ('GMAIL', 'Gmail / Google Workspace'), ('MICROSOFT', 'Outlook.com / Microsoft 365')], help_text='The OAuth provider.', max_length=20)),
                ('protocol', models.CharField(choices=[('IMAP', 'IMAP: folders, flags and moves live on the server'), ('POP3', 'POP3: one inbox, downloaded; flags are local')], default='IMAP', help_text='How the linked mailbox is read.', max_length=10)),
                ('state', models.CharField(help_text="Opaque value tying the provider's redirect back to this attempt.", max_length=100, unique=True)),
                ('code_verifier', models.TextField(help_text='Encrypted PKCE verifier. Never exposed.')),
                ('redirect_url', models.CharField(help_text='Where the provider redirects after approval.', max_length=2000)),
                ('auth_url', models.TextField(help_text='What the client opens.')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for the user to approve at the provider'), ('COMPLETED', 'Approved; the mailbox is linked')], default='PENDING', help_text='Where the link is.', max_length=10)),
                ('name', models.CharField(blank=True, default='', help_text='The display name the new mailbox gets.', max_length=200)),
                ('expires_at', models.DateTimeField(help_text='A link not completed by then is refused.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the link was started.')),
                ('account', models.ForeignKey(blank=True, help_text='The mailbox it re-links, or the one it linked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_links', to='mail.mailaccount')),
                ('creator', models.ForeignKey(help_text='The member who started it; only they complete, resume or cancel it.', on_delete=django.db.models.deletion.CASCADE, related_name='mail_oauth_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization the link was started in.', on_delete=django.db.models.deletion.CASCADE, related_name='mail_oauth_links', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENDING', 'Being handed to the SMTP server'), ('SENT', 'Accepted by the SMTP server'), ('FAILED', 'Refused or not delivered to the SMTP server')], default='SENDING', help_text='Where the message is.', max_length=10)),
                ('to', models.JSONField(default=list, help_text='To addresses: [{name, address}].')),
                ('cc', models.JSONField(blank=True, default=list, help_text='Cc addresses: [{name, address}].')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='Bcc addresses: [{name, address}].')),
                ('subject', models.TextField(blank=True, default='', help_text='The subject.')),
                ('text_body', models.TextField(blank=True, default='', help_text='The plain-text body.')),
                ('html_body', models.TextField(blank=True, default='', help_text='The HTML body, as given.')),
                ('message_id', models.CharField(help_text='The Message-ID given to the message.', max_length=998)),
                ('refused', models.JSONField(blank=True, default=dict, help_text='Recipients the SMTP server refused, with its answer.')),
                ('saved_to_sent', models.BooleanField(default=False, help_text='A copy was appended to the Sent folder.')),
                ('error', models.TextField(blank=True, help_text='Why sending failed.', null=True)),
                ('error_code', models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error')], help_text='The machine-readable kind of `error`.', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When sending was asked for.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the SMTP server accepted it.', null=True)),
                ('account', models.ForeignKey(help_text='The mailbox it is sent from.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='mail.mailaccount')),
                ('attachments', models.ManyToManyField(blank=True, help_text='Uploaded files attached to the message.', related_name='+', to='datalayer.bigfilestore')),
                ('creator', models.ForeignKey(blank=True, help_text='The member who sent it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mail', to=settings.AUTH_USER_MODEL)),
                ('in_reply_to', models.ForeignKey(blank=True, help_text='The message this answers (sets In-Reply-To/References).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOutgoingMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENDING', 'Being handed to the SMTP server'), ('SENT', 'Accepted by the SMTP server'), ('FAILED', 'Refused or not delivered to the SMTP server')], default='SENDING', help_text='Where the message is.', max_length=10)),
                ('to', models.JSONField(default=list, help_text='To addresses: [{name, address}].')),
                ('cc', models.JSONField(blank=True, default=list, help_text='Cc addresses: [{name, address}].')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='Bcc addresses: [{name, address}].')),
                ('subject', models.TextField(blank=True, default='', help_text='The subject.')),
                ('text_body', models.TextField(blank=True, default='', help_text='The plain-text body.')),
                ('html_body', models.TextField(blank=True, default='', help_text='The HTML body, as given.')),
                ('message_id', models.CharField(help_text='The Message-ID given to the message.', max_length=998)),
                ('refused', models.JSONField(blank=True, default=dict, help_text='Recipients the SMTP server refused, with its answer.')),
                ('saved_to_sent', models.BooleanField(default=False, help_text='A copy was appended to the Sent folder.')),
                ('error', models.TextField(blank=True, help_text='Why sending failed.', null=True)),
                ('error_code', models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error')], help_text='The machine-readable kind of `error`.', max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When sending was asked for.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the SMTP server accepted it.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The member who sent it.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('account', models.ForeignKey(blank=True, db_constraint=False, help_text='The mailbox it is sent from.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mail.mailaccount')),
                ('in_reply_to', models.ForeignKey(blank=True, db_constraint=False, help_text='The message this answers (sets In-Reply-To/References).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mail.message')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='mail.outgoingmessage')),
            ],
            options={
                'verbose_name': 'historical outgoing message',
                'verbose_name_plural': 'historical outgoing messages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, default='', help_text='The subject without Re:/Fwd: prefixes.')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='The date of the newest message.', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='How many messages are in the conversation.')),
                ('account', models.ForeignKey(help_text='The mailbox the conversation is in.', on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mail.mailaccount')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='The conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mail.thread'),
        ),
        migrations.AddConstraint(
            model_name='mailaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'creator', 'email_address', 'protocol'), name='mail_account_unique_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='mailfolder',
            constraint=models.UniqueConstraint(fields=('account', 'path'), name='mail_folder_account_path'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('message', 'position'), name='mail_att_message_position'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['account', '-last_message_at'], name='mail_thread_recent'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['folder', '-date'], name='mail_msg_folder_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', '-date'], name='mail_msg_account_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'message_id'], name='mail_msg_account_mid'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['embedding_model'], name='mail_msg_emb_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('uid__isnull', False)), fields=('folder', 'uidvalidity', 'uid'), name='mail_msg_folder_uid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('uidl__isnull', False)), fields=('folder', 'uidl'), name='mail_msg_folder_uidl'),
        ),
    ]
