# Generated by Django 6.0.6 on 2026-09-28 11:56

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        ('mail', '0002_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The category's name.", max_length=200)),
                ('color', models.CharField(blank=True, default='', help_text='A display color (e.g. #4f86f7).', max_length=20)),
                ('sync', models.CharField(choices=[('LOCAL', 'Only here; the server never sees it'), ('KEYWORD', 'As an IMAP keyword on the server, so other mail clients see it')], default='LOCAL', help_text='Where the category lives.', max_length=10)),
                ('keyword', models.CharField(help_text='The IMAP keyword (e.g. $Invoices) a KEYWORD category is kept as.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created.')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(help_text="The message's key.", max_length=998)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When.')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="The category's name.", max_length=200)),
                ('color', models.CharField(blank=True, default='', help_text='A display color (e.g. #4f86f7).', max_length=20)),
                ('sync', models.CharField(choices=[('LOCAL', 'Only here; the server never sees it'), ('KEYWORD', 'As an IMAP keyword on the server, so other mail clients see it')], default='LOCAL', help_text='Where the category lives.', max_length=10)),
                ('keyword', models.CharField(help_text='The IMAP keyword (e.g. $Invoices) a KEYWORD category is kept as.', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the category was created.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical category',
                'verbose_name_plural': 'historical categorys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LocalPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(help_text="The message's key.", max_length=998)),
                ('add', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Flags set here.')),
                ('remove', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Flags cleared here.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the pin last changed.')),
            ],
        ),
        migrations.CreateModel(
            name='MailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(help_text="The message's key, to find it again.", max_length=998)),
                ('kind', models.CharField(choices=[('FLAGS', 'Add and remove flags and keywords (STORE)'), ('MOVE', 'Move the message to another folder'), ('EXPUNGE', 'Delete the message for good'), ('POP_DELE', 'Delete the message on a POP3 server')], help_text='What the change does.', max_length=10)),
                ('state', models.CharField(choices=[('PENDING', 'Waiting to be pushed (from `pushAfter` on)'), ('FAILED', 'The server refused it or it ran out of attempts; the local state stays')], default='PENDING', help_text='Where the change is.', max_length=10)),
                ('add', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='FLAGS: flags and keywords to add.')),
                ('remove', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='FLAGS: flags and keywords to remove.')),
                ('origin_uidvalidity', models.BigIntegerField(blank=True, help_text='MOVE/EXPUNGE: the UIDVALIDITY of the UID.', null=True)),
                ('origin_uid', models.BigIntegerField(blank=True, help_text="MOVE/EXPUNGE: the message's UID there.", null=True)),
                ('origin_uidl', models.CharField(blank=True, help_text="POP_DELE: the message's UIDL.", max_length=100, null=True)),
                ('push_after', models.DateTimeField(help_text='Not pushed before then: the undo window, or the backoff after a failure.')),
                ('attempts', models.IntegerField(default=0, help_text='Failed attempts so far.')),
                ('error', models.TextField(blank=True, help_text='Why the last attempt failed.', null=True)),
                ('error_code', models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error'), ('UNSUPPORTED_BY_POLICY', 'The mailbox is set not to change this on the server (its push settings)'), ('KEYWORDS_NOT_PERMITTED', 'The folder does not keep keywords (no \\* in PERMANENTFLAGS); the category stays local'), ('MESSAGE_GONE', 'The message is no longer where the change expected it on the server'), ('UNSAFE_EXPUNGE', 'Without UIDPLUS an expunge would also remove other deleted messages of the folder')], help_text='The machine-readable kind of `error`.', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the change was made.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the change last changed (coalesced, retried).')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='historicalmailaccount',
            name='push_deletes',
            field=models.BooleanField(default=True, help_text='Push deletes to the server. Off only hides deleted mail here.'),
        ),
        migrations.AddField(
            model_name='historicalmailaccount',
            name='push_flagged',
            field=models.BooleanField(default=True, help_text='Push flagging (\\Flagged) to the server. Off keeps it local.'),
        ),
        migrations.AddField(
            model_name='historicalmailaccount',
            name='push_keywords',
            field=models.BooleanField(default=True, help_text='Push keywords (KEYWORD categories, $Label…) to the server. Off keeps them local.'),
        ),
        migrations.AddField(
            model_name='historicalmailaccount',
            name='push_moves',
            field=models.BooleanField(default=True, help_text='Push moves (and archiving) to the server. Off refuses moves: a folder only exists on the server.'),
        ),
        migrations.AddField(
            model_name='historicalmailaccount',
            name='push_seen',
            field=models.BooleanField(default=True, help_text='Push read/unread (\\Seen) to the server. Off keeps it local.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='push_deletes',
            field=models.BooleanField(default=True, help_text='Push deletes to the server. Off only hides deleted mail here.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='push_flagged',
            field=models.BooleanField(default=True, help_text='Push flagging (\\Flagged) to the server. Off keeps it local.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='push_keywords',
            field=models.BooleanField(default=True, help_text='Push keywords (KEYWORD categories, $Label…) to the server. Off keeps them local.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='push_moves',
            field=models.BooleanField(default=True, help_text='Push moves (and archiving) to the server. Off refuses moves: a folder only exists on the server.'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='push_seen',
            field=models.BooleanField(default=True, help_text='Push read/unread (\\Seen) to the server. Off keeps it local.'),
        ),
        migrations.AddField(
            model_name='mailfolder',
            name='keywords_allowed',
            field=models.BooleanField(default=True, help_text='The folder keeps any keyword (\\* in PERMANENTFLAGS); assumed until a push sees otherwise.'),
        ),
        migrations.AddField(
            model_name='mailfolder',
            name='permanent_flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='The PERMANENTFLAGS the server announced when the folder was last changed.'),
        ),
        migrations.AddField(
            model_name='mailfolder',
            name='server_unread_count',
            field=models.IntegerField(default=0, help_text='Unread messages in the folder, as the server counts them.'),
        ),
        migrations.AddField(
            model_name='message',
            name='category_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='The categories the message is in (materialized, see mail.overlay).'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deleted here; hidden, and gone once the delete reaches the server.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_key',
            field=models.CharField(blank=True, default='', help_text='What local state (pins, categories) is kept under: the Message-ID, else a hash of the headers.', max_length=998),
        ),
        migrations.AddField(
            model_name='message',
            name='server_flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='The flags as the server last had them.'),
        ),
        migrations.AlterField(
            model_name='historicaloutgoingmessage',
            name='error_code',
            field=models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error'), ('UNSUPPORTED_BY_POLICY', 'The mailbox is set not to change this on the server (its push settings)'), ('KEYWORDS_NOT_PERMITTED', 'The folder does not keep keywords (no \\* in PERMANENTFLAGS); the category stays local'), ('MESSAGE_GONE', 'The message is no longer where the change expected it on the server'), ('UNSAFE_EXPUNGE', 'Without UIDPLUS an expunge would also remove other deleted messages of the folder')], help_text='The machine-readable kind of `error`.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='last_error_code',
            field=models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error'), ('UNSUPPORTED_BY_POLICY', 'The mailbox is set not to change this on the server (its push settings)'), ('KEYWORDS_NOT_PERMITTED', 'The folder does not keep keywords (no \\* in PERMANENTFLAGS); the category stays local'), ('MESSAGE_GONE', 'The message is no longer where the change expected it on the server'), ('UNSAFE_EXPUNGE', 'Without UIDPLUS an expunge would also remove other deleted messages of the folder')], help_text='The machine-readable kind of `last_error`.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mailfolder',
            name='unread_count',
            field=models.IntegerField(default=0, help_text='Unread messages in the folder, as they are here (local changes included).'),
        ),
        migrations.AlterField(
            model_name='message',
            name='flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="The effective flags and keywords (\\Seen, \\Flagged, \\Answered, \\Draft, $Label…): the server's with local changes applied."),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='error_code',
            field=models.CharField(blank=True, choices=[('NOT_CONFIGURED', 'The service is not configured for this (an OAuth client, the datalayer)'), ('AUTH_FAILED', 'The server refused the username or password'), ('CONSENT_EXPIRED', 'The OAuth grant was revoked or ran out; link the mailbox again'), ('CONNECTION_FAILED', 'The server could not be reached, or the connection broke'), ('TLS_FAILED', 'The TLS handshake failed (certificate or protocol)'), ('TLS_REQUIRED', 'The mailbox asks for a connection without TLS, which is not allowed'), ('HOST_NOT_ALLOWED', 'The host resolves to a private or internal address'), ('SYNC_IN_PROGRESS', 'Another sync holds this mailbox right now'), ('RATE_LIMITED', 'Synced too recently; try again later'), ('SERVER_ERROR', 'The server answered a command with an error'), ('SEND_REJECTED', 'The SMTP server refused the message or a recipient'), ('UNSUPPORTED_BY_PROTOCOL', 'POP3 cannot do this (folders, flags on the server)'), ('MAILBOX_INACTIVE', 'The mailbox is disabled or needs new credentials'), ('INVALID_STATE', 'The link state is unknown, used or belongs to someone else'), ('CODE_EXPIRED', 'The link was not completed in time'), ('PROVIDER_ERROR', 'The OAuth provider answered with an error'), ('UNSUPPORTED_BY_POLICY', 'The mailbox is set not to change this on the server (its push settings)'), ('KEYWORDS_NOT_PERMITTED', 'The folder does not keep keywords (no \\* in PERMANENTFLAGS); the category stays local'), ('MESSAGE_GONE', 'The message is no longer where the change expected it on the server'), ('UNSAFE_EXPUNGE', 'Without UIDPLUS an expunge would also remove other deleted messages of the folder')], help_text='The machine-readable kind of `error`.', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'message_key'], name='mail_msg_account_key'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category_ids'], name='mail_msg_categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(help_text='The mailbox.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mail.mailaccount'),
        ),
        migrations.AddField(
            model_name='categoryassignment',
            name='account',
            field=models.ForeignKey(help_text='The mailbox.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mail.mailaccount'),
        ),
        migrations.AddField(
            model_name='categoryassignment',
            name='category',
            field=models.ForeignKey(help_text='The category.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mail.category'),
        ),
        migrations.AddField(
            model_name='categoryassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who put the message there.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The mailbox.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mail.mailaccount'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='mail.category'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='localpin',
            name='account',
            field=models.ForeignKey(help_text='The mailbox.', on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='mail.mailaccount'),
        ),
        migrations.AddField(
            model_name='mailchange',
            name='account',
            field=models.ForeignKey(help_text='The mailbox.', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='mail.mailaccount'),
        ),
        migrations.AddField(
            model_name='mailchange',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The member who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailchange',
            name='message',
            field=models.ForeignKey(blank=True, help_text='The row the change was made on (null once sync replaced it).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='mail.message'),
        ),
        migrations.AddField(
            model_name='mailchange',
            name='origin_folder',
            field=models.ForeignKey(blank=True, help_text='MOVE/EXPUNGE: the folder the message is in on the server.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.mailfolder'),
        ),
        migrations.AddField(
            model_name='mailchange',
            name='target_folder',
            field=models.ForeignKey(blank=True, help_text='MOVE: the folder the message goes to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.mailfolder'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='mail_cat_account_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('account'), django.db.models.functions.text.Lower('keyword'), name='mail_cat_account_keyword'),
        ),
        migrations.AddIndex(
            model_name='categoryassignment',
            index=models.Index(fields=['account', 'message_key'], name='mail_catassign_key'),
        ),
        migrations.AddConstraint(
            model_name='categoryassignment',
            constraint=models.UniqueConstraint(fields=('category', 'message_key'), name='mail_catassign_unique'),
        ),
        migrations.AddConstraint(
            model_name='localpin',
            constraint=models.UniqueConstraint(fields=('account', 'message_key'), name='mail_pin_account_key'),
        ),
        migrations.AddIndex(
            model_name='mailchange',
            index=models.Index(fields=['state', 'push_after'], name='mail_change_due'),
        ),
        migrations.AddIndex(
            model_name='mailchange',
            index=models.Index(fields=['account', 'message_key'], name='mail_change_key'),
        ),
        migrations.AddConstraint(
            model_name='mailchange',
            constraint=models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('message', 'kind'), name='mail_change_one_per_kind'),
        ),
    ]


def _key(message_id, sender_address, date, subject, size):  # a copy of mail.overlay.key_parts, frozen here
    import hashlib

    if message_id:
        return message_id
    stamp = str(int(date.timestamp())) if date else ""
    return "h:" + hashlib.sha256(f"{sender_address}\n{stamp}\n{subject}\n{size}".encode()).hexdigest()[:40]


def fill(apps, schema_editor):
    """What the server said is what the rows had; keys for local state; the server's unread counts."""
    Message = apps.get_model("mail", "Message")
    MailFolder = apps.get_model("mail", "MailFolder")
    rows = []
    for row in Message.objects.only("id", "flags", "message_id", "sender_address", "date", "subject", "size").iterator(chunk_size=2000):
        row.server_flags = list(row.flags)
        row.message_key = _key(row.message_id, row.sender_address, row.date, row.subject, row.size)
        rows.append(row)
        if len(rows) >= 2000:
            Message.objects.bulk_update(rows, ["server_flags", "message_key"])
            rows = []
    Message.objects.bulk_update(rows, ["server_flags", "message_key"])
    MailFolder.objects.update(server_unread_count=models.F("unread_count"))


Migration.operations.append(migrations.RunPython(fill, migrations.RunPython.noop))
