# Generated by Django 6.0.6 on 2026-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_local_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthlink',
            name='claimed_until',
            field=models.DateTimeField(blank=True, help_text='Held by a completion until then, so one request exchanges the code at a time.', null=True),
        ),
        migrations.AddField(
            model_name='oauthlink',
            name='error_code',
            field=models.CharField(blank=True, help_text='FAILED: the machine-readable kind of failure (a MailErrorCode).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='oauthlink',
            name='error_message',
            field=models.TextField(blank=True, help_text='FAILED: one sentence for the user.', null=True),
        ),
        migrations.AlterField(
            model_name='oauthlink',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the user to approve at the provider'), ('COMPLETED', 'Approved; the mailbox is linked'), ('FAILED', 'The provider refused, or the login ran out'), ('CANCELLED', 'The user dropped the login before it was finished')], default='PENDING', help_text='Where the link is.', max_length=10),
        ),
    ]
